<?php
require_once __DIR__ . '/config/db.php';
require_once __DIR__ . '/includes/functions.php';
$publicTitle='Home';
$departments=$pdo->query("SELECT * FROM departments ORDER BY id LIMIT 4")->fetchAll();
$doctors=$pdo->query("SELECT d.*, dep.department_name FROM doctors d LEFT JOIN departments dep ON dep.id=d.department_id WHERE d.status='active' ORDER BY d.id LIMIT 3")->fetchAll();
include __DIR__ . '/includes/public-header.php';
?>
<section class="hero"><div class="container"><div class="hero-content">
  <div class="hero-badges"><span><i class="fa-solid fa-shield-heart"></i> Trusted Care</span><span><i class="fa-solid fa-truck-medical"></i> 24/7 Emergency</span><span><i class="fa-solid fa-user-doctor"></i> Expert Doctors</span></div>
  <div class="hero-kicker">Advanced care, human touch</div><h1>Excellence in healthcare with compassionate care.</h1>
  <p>MediCore brings doctors, departments, appointments and patient-focused services together in one modern hospital experience.</p>
  <div class="hero-actions"><a class="btn btn-main" href="patient/login.php">Patient Login <i class="fa-solid fa-arrow-right ms-1"></i></a><a class="btn btn-ghost" href="#doctors"><i class="fa-solid fa-user-doctor me-2"></i>Find a Doctor</a></div>
</div></div></section>
<section class="quick-strip"><div class="container"><div class="row g-3">
<?php foreach([['fa-truck-medical','Emergency Care','24/7 immediate medical support'],['fa-calendar-check','Easy Appointments','Book a doctor in a few clicks'],['fa-microscope','Diagnostics','Reliable testing and reporting'],['fa-pills','Pharmacy Support','Medicine and stock services']] as $q): ?><div class="col-md-6 col-xl-3"><div class="quick-card"><div class="quick-icon"><i class="fa-solid <?= $q[0] ?>"></i></div><div><h5><?= $q[1] ?></h5><p><?= $q[2] ?></p></div></div></div><?php endforeach; ?>
</div></div></section>
<section class="section" id="about"><div class="container"><div class="row align-items-center g-5"><div class="col-lg-6"><div class="about-image"><div class="about-float"><strong>24/7</strong><div class="fw-bold">Patient support</div><small class="text-secondary">Care when you need it</small></div></div></div><div class="col-lg-6"><div class="section-kicker">About MediCore</div><h2 class="section-title">Compassionate care backed by modern hospital management.</h2><p class="section-text">Our hospital website connects patients with core healthcare information while the internal system supports doctors, appointments, admissions, medicines and billing.</p><div class="row g-3 mt-2"><?php foreach([['fa-stethoscope','Specialist care'],['fa-heart-pulse','Patient-first approach'],['fa-flask-vial','Modern diagnostics'],['fa-user-shield','Secure records']] as $x): ?><div class="col-6"><div class="feature-card"><div class="feature-icon"><i class="fa-solid <?= $x[0] ?>"></i></div><h5><?= $x[1] ?></h5><p>Reliable support designed around safer and smoother hospital visits.</p></div></div><?php endforeach; ?></div><a class="btn btn-main mt-4" href="#about">Learn More About Us</a></div></div></div></section>
<section class="stats-band"><div class="container"><div class="row g-4"><?php foreach([[25,'+','Years of Care'],[50,'+','Medical Experts'],[12,'+','Departments'],[10000,'+','Patients Served']] as $s): ?><div class="col-6 col-lg-3"><div class="stat-public"><strong class="counter" data-target="<?= $s[0] ?>" data-suffix="<?= $s[1] ?>">0</strong><span><?= $s[2] ?></span></div></div><?php endforeach; ?></div></div></section>
<section class="section section-soft" id="departments"><div class="container"><div class="text-center mx-auto mb-5" style="max-width:700px"><div class="section-kicker">Departments</div><h2 class="section-title">Specialized care for every stage of life</h2><p class="section-text">Explore hospital departments and connect with the right medical team.</p></div><div class="row g-4">
<?php $icons=['fa-heart-pulse','fa-brain','fa-bone','fa-child-reaching']; foreach($departments as $i=>$d): ?><div class="col-md-6 col-xl-3"><div class="dept-card"><div class="dept-icon"><i class="fa-solid <?= $icons[$i%count($icons)] ?>"></i></div><h5><?= e($d['department_name']) ?></h5><p><?= e($d['description'] ?: 'Specialized diagnosis, treatment and patient support.') ?></p><a class="small fw-bold text-decoration-none" style="color:var(--p)" href="#departments">Explore Department <i class="fa-solid fa-arrow-right ms-1"></i></a></div></div><?php endforeach; ?>
</div><div class="text-center mt-4"><a class="btn btn-main" href="#departments">View All Departments</a></div></div></section>
<section class="section" id="doctors"><div class="container"><div class="d-flex justify-content-between align-items-end gap-3 flex-wrap mb-4"><div><div class="section-kicker">Our Doctors</div><h2 class="section-title mb-0">Meet our medical experts</h2></div><a href="#doctors" class="btn btn-outline-secondary">View All Doctors</a></div><div class="row g-4">
<?php $photos=['https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&w=700&q=85','https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=700&q=85','https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=700&q=85']; foreach($doctors as $i=>$d): ?><div class="col-md-6 col-lg-4"><div class="doctor-card"><img class="doctor-photo" src="<?= $photos[$i%3] ?>" alt="Doctor"><div class="doctor-body"><div class="spec"><?= e($d['department_name'] ?: 'Medical Department') ?></div><h5><?= e($d['name']) ?></h5><div class="doctor-meta"><i class="fa-solid fa-stethoscope me-1"></i><?= e($d['specialization']) ?> · Consultation <?= money($d['fee']) ?></div><a class="btn btn-main mt-3" href="appointment.php?doctor=<?= (int)$d['id'] ?>">Book Now</a></div></div></div><?php endforeach; ?>
</div></div></section>
<section class="section pt-0"><div class="container"><div class="cta"><div class="row align-items-center position-relative" style="z-index:2"><div class="col-lg-8"><div class="section-kicker text-white">Need medical support?</div><h2 class="fw-bold">Schedule your consultation today.</h2><p class="mb-lg-0" style="color:#d5eeeb">Choose a doctor, preferred date and time. Your appointment is saved directly in the hospital system.</p></div><div class="col-lg-4 text-lg-end mt-3 mt-lg-0"><a class="btn btn-light fw-bold" href="patient/login.php">Book Appointment</a></div></div></div></div></section>
<?php include __DIR__ . '/includes/public-footer.php'; ?>
