<?php
require_once __DIR__.'/../includes/patient-auth.php';requirePatientLogin();require_once __DIR__.'/../config/db.php';require_once __DIR__.'/../includes/functions.php';
$u=currentPatientUser();$success='';$error='';$doctors=$pdo->query("SELECT d.id,d.name,d.specialization,dep.department_name FROM doctors d LEFT JOIN departments dep ON dep.id=d.department_id WHERE d.status='active' ORDER BY d.name")->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){try{$doctorId=(int)post('doctor_id');$date=post('appointment_date');$time=post('appointment_time');$reason=post('reason');if(!$doctorId||!$date||!$time||!$reason)throw new RuntimeException('Please complete all fields.');if($date<date('Y-m-d'))throw new RuntimeException('Please choose today or a future date.');$st=$pdo->prepare("INSERT INTO appointments(patient_id,doctor_id,appointment_date,appointment_time,reason,status,notes,created_at) VALUES(?,?,?,?,?,'pending','Patient portal request',NOW())");$st->execute([(int)$u['patient_id'],$doctorId,$date,$time,$reason]);$success='Appointment request submitted. Current status: Pending. You can track confirmation in My Panel.';}catch(Throwable $e){$error=$e->getMessage();}}
$publicTitle='Book Appointment';include __DIR__.'/../includes/public-header.php';
?>
<section class="patient-portal-head compact"><div class="container"><div class="portal-code">PATIENT PORTAL</div><h1>Book Appointment</h1><p>Your request will be visible to hospital staff for confirmation.</p></div></section><section class="section section-soft"><div class="container"><div class="appointment-wrap"><div class="row g-0"><div class="col-lg-4"><div class="appointment-side"><h3 class="fw-bold">Booking as <?= e($u['name']) ?></h3><p style="color:#d4efec">Your patient account is automatically attached to this request.</p><a href="dashboard.php" class="btn btn-light mt-3">Back to My Panel</a></div></div><div class="col-lg-8"><div class="appointment-form"><?php if($success):?><div class="alert alert-success alert-modern"><?= e($success) ?></div><?php endif;?><?php if($error):?><div class="alert alert-danger alert-modern"><?= e($error) ?></div><?php endif;?>
<form method="post"><div class="row g-3"><div class="col-12"><label class="form-label">Doctor *</label><select class="form-select" name="doctor_id" required><option value="">Select Doctor</option><?php foreach($doctors as $d):?><option value="<?= $d['id'] ?>"><?= e($d['name'].' — '.$d['specialization']) ?></option><?php endforeach;?></select></div><div class="col-md-6"><label class="form-label">Date *</label><input class="form-control" type="date" name="appointment_date" min="<?= date('Y-m-d') ?>" required></div><div class="col-md-6"><label class="form-label">Time *</label><input class="form-control" type="time" name="appointment_time" required></div><div class="col-12"><label class="form-label">Reason for Visit *</label><textarea class="form-control" name="reason" rows="4" required></textarea></div><div class="col-12"><button class="btn btn-main">Submit Request</button></div></div></form></div></div></div></div></div></section>
<?php include __DIR__.'/../includes/public-footer.php'; ?>
