<?php
require_once __DIR__.'/../includes/patient-auth.php';requirePatientLogin();require_once __DIR__.'/../config/db.php';require_once __DIR__.'/../includes/functions.php';
$u=currentPatientUser();$pid=(int)$u['patient_id'];
$st=$pdo->prepare("SELECT a.*, d.name doctor_name, d.specialization, dep.department_name FROM appointments a JOIN doctors d ON d.id=a.doctor_id LEFT JOIN departments dep ON dep.id=d.department_id WHERE a.patient_id=? ORDER BY a.appointment_date DESC,a.appointment_time DESC");$st->execute([$pid]);$appointments=$st->fetchAll();
$counts=['pending'=>0,'confirmed'=>0,'completed'=>0,'cancelled'=>0];foreach($appointments as $a){if(isset($counts[$a['status']]))$counts[$a['status']]++;}
$publicTitle='My Patient Panel';include __DIR__.'/../includes/public-header.php';
?>
<section class="patient-portal-head"><div class="container"><div class="d-flex justify-content-between align-items-center flex-wrap gap-3"><div><div class="portal-code"><?= e($u['patient_code']) ?></div><h1>Hello, <?= e($u['name']) ?></h1><p>Here you can see only your appointment requests and their latest confirmation status.</p></div><a class="btn btn-light fw-bold" href="appointment.php"><i class="fa-regular fa-calendar-plus me-2"></i>Book New Appointment</a></div></div></section>
<section class="section section-soft"><div class="container"><div class="row g-3 mb-4"><?php foreach([['pending','Pending','fa-clock'],['confirmed','Confirmed','fa-circle-check'],['completed','Completed','fa-check-double'],['cancelled','Cancelled','fa-circle-xmark']] as $x): ?><div class="col-6 col-lg-3"><div class="portal-stat"><div class="portal-stat-icon"><i class="fa-solid <?= $x[2] ?>"></i></div><strong><?= $counts[$x[0]] ?></strong><span><?= $x[1] ?></span></div></div><?php endforeach; ?></div>
<div class="panel portal-panel"><div class="panel-header"><div><h2 class="panel-title">My Appointments</h2><p class="panel-subtitle">Hospital staff updates appear here automatically</p></div></div><div class="table-responsive"><table class="table"><thead><tr><th>Doctor</th><th>Date & Time</th><th>Reason</th><th>Status</th></tr></thead><tbody><?php if(!$appointments): ?><tr><td colspan="4"><div class="empty-state"><i class="fa-regular fa-calendar-xmark"></i><div>No appointments yet.</div><a class="btn btn-main mt-3" href="appointment.php">Book Your First Appointment</a></div></td></tr><?php endif; ?><?php foreach($appointments as $a): ?><tr><td><strong><?= e($a['doctor_name']) ?></strong><br><small class="text-secondary"><?= e($a['specialization']) ?></small></td><td><?= e(date('d M Y',strtotime($a['appointment_date']))) ?><br><small><?= e(date('h:i A',strtotime($a['appointment_time']))) ?></small></td><td><?= e($a['reason']) ?></td><td><span class="appointment-status status-<?= e($a['status']) ?>"><i class="fa-solid <?= $a['status']==='confirmed'?'fa-circle-check':($a['status']==='completed'?'fa-check-double':($a['status']==='cancelled'?'fa-circle-xmark':'fa-clock')) ?>"></i><?= e(ucfirst($a['status'])) ?></span></td></tr><?php endforeach; ?></tbody></table></div></div></div></section>
<?php include __DIR__.'/../includes/public-footer.php'; ?>
